[build]
    base = ""
    command = "npm run build --configuration=production"
    publish = "dist/catan-game-random-generator/browser"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
